site_name: FavoriteFiles Documentation
site_url: https://codebyzach.github.io/sublime_favorite_files
repo_url: https://github.com/CodeByZach/sublime_favorite_files
edit_uri: tree/master/docs/src/markdown
site_description: Sublime Text plugin for saving and accessing favorite files.
copyright: |
  Copyright &copy; 2011 - 2017 <a href="https://github.com/facelessuser">Isaac Muse</a>
  <br><span class="md-footer-custom-text">emoji provided free by </span><a href="http://www.emojione.com">EmojiOne</a>

nav:
  - Installation: installation.md
  - User Guide: index.md
  - Contributing & Support: contributing.md
  - License: license.md

docs_dir: docs/src/markdown
theme:
  name: material
  custom_dir: docs/theme
  features:
    - content.code.copy
    - navigation.tracking
    - navigation.sections

markdown_extensions:
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs/src/markdown/_snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.keys:
      separator: "+"
  - def_list
  - attr_list
  - md_in_html
  - tables
  - abbr

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CodeByZach
      name: CodeByZach on GitHub

extra_css:
  - extra-00833721db.css
extra_javascript:
  - extra-4596f9831a.js
