name: Documentation

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get install -y aspell aspell-en

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install -r docs/requirements.txt

      - name: Build documentation
        run: mkdocs build --clean --verbose --strict

      - name: Deploy to GitHub Pages
        uses: actions/configure-pages@v3

      - name: Publish to GitHub Pages
        id: publish
        uses: actions/upload-pages-artifact@v1
        with:
          path: site

      - name: Release GitHub Pages
        uses: actions/deploy-pages@v1
        if: ${{ always() }}
