name: Tests

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
  workflow_dispatch:

concurrency:
  group: tests-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get install -y aspell aspell-en

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Run tests, lint, spellcheck & docs build
        run: |
          pytest .
          flake8 .
          python tests/spellcheck.py
          mkdocs build --clean --verbose --strict
